---
- name: Install RedHat stuff
  block:
  - name: Disable SELinux since not all tasks work with it
    selinux:
      state: permissive
      policy: targeted

  - name: Enable OpenStack Repository
    package:
      name: centos-release-openstack-{{ openstack_version }}
      state: present

  - name: Enable PowerTools
    lineinfile:
      path: /etc/yum.repos.d/CentOS-Stream-PowerTools.repo
      regexp: 'enabled=0'
      line: 'enabled=1'

  - name: Install OpenStack-SELinux
    package:
      name: openstack-selinux
      state: present
  when: ansible_os_family == "RedHat"

- name: Install Debian stuff
  block:
  - name: Add ubuntu cloud archive key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 5EDB1B62EC4926EA

  - name: Enable OpenStack Repository
    apt_repository:
      repo: "deb http://ubuntu-cloud.archive.canonical.com/ubuntu focal-updates/{{ openstack_version }} main"
      filename: openstack-{{ openstack_version }}
      #    update_cache: false

  - name: Update apt Cache
    apt:
      update_cache: true
      cache_valid_time: 3600

  - name: Make sure apt-utils are installed
    package:
      name: apt-utils
      state: present
  when: ansible_os_family == "Debian"

- name: Build /etc/hosts file
  blockinfile:
    create: true
    path: /etc/hosts
    block: |
        {{ hostvars[groups['controller_hosts'][0]]['ansible_facts'][management_interface]['ipv4']['address'] }} controller
        {% for host in groups['all'] %}
        {{ hostvars[host]['ansible_facts'][management_interface]['ipv4']['address'] }} {{ host }}
        {% endfor %}

- name: Install base packages
  package:
    name: "{{ base_packages }}"
    state: present

- name: install chrony
  package:
    name: chrony
    state: present

- name: configure chrony
  template:
    src: etc/chrony.conf.j2
    dest: "{{ chrony.conf_destination[ansible_os_family] }}"
  notify:
  - restart chronyd

- name: enable chronyd
  service:
    name: chronyd
    enabled: true

- name: Install OpenStack Client
  package:
    name: python3-openstackclient
    state: present
